### ISSUE TITLE
Let TreeEditor.ModelService implementation be asynchronous

### ISSUE THREAD

**Issue by vhemery** [eclipse-emfcloud/theia-tree-editor#21]
The `TreeEditor.ModelService` methods are currently synchronous with fixed type results.
As a consequence, it is currently impossible to implement it by relying on the @eclipse-emfcloud/modelserver-theia `ModelServerClient` which returns a `Promise` object to get type schema and the UI schema.

To allow asynchronous usage, it would be nice to change methods return types to MaybePromise (from @theia/core).
For example `getSchemaForNode(node: TreeEditor.Node) : JsonSchema | undefined`
would become `getSchemaForNode(node: TreeEditor.Node) : MaybePromise<JsonSchema> | undefined`

This way, previous implementations would still be compatible with the new interface, but implementations can also work in an asynchronous way.

The drawback is that all callers of these methods must then handle the asynchronous behavior.
So I'm not sure it is feasible everywhere... especially when looking at `AddCommandHandler#isVisible(treeAnchor: TreeAnchor)` method which use the modelService and itself implement the `CommandHandler` interface from @theia/core
(and we could legitimately expect getChildrenMapping to have and asynchronous implementation)

**Comment by vhemery** [comment]
PR https://github.com/eclipse-emfcloud/theia-tree-editor/pull/28
This PR takes care only of the TreeEditor.ModelService. If you think it is relevant and there is no need for opening an extra bug, I can update it with  TreeEditor.NodeFactory  changes.
As stated, getChildrenMapping and getNameForType methods have been intentionnally not updated. Updating them would require theia/core changes on the command framework, and that's probably not suitable.

**Comment by vhemery** [comment]
Added changes to PR #28 to make TreeEditor.NodeFactory possibly asynchronous. (except hasCreatableChildren which can't)
On both these commits, please note that the tree-editor-example is intentionnally **not** updated simply because it is **not impacted**. (that's the magic with MaybePromise)
I can not guarantee on the other hand that the coffee editor example would not be impacted.

**Comment by lucas-koehler** [comment]
@vhemery Thanks for your contributions. It is fine if the coffee editor needs small adaptions after these changes. I left a more detailed review in the PR.

**Comment by vhemery** [comment]
PR #30 should be OK.

**Comment by lucas-koehler** [comment]
@vhemery Thanks again for your contribution. The changes should now be available in the `@eclipse-emfcloud/theia-tree-editor` packages via the `next` version tag. They will also be available via the `latest` tag at a later point in time.
