### ISSUE TITLE
quality: fix 'Containter' typo

### ISSUE THREAD

**Issue by vince-fugnitto** [eclipse-emfcloud/theia-tree-editor#25]
**Description**

The typo `Containter` should be fixed in the extension:

https://github.com/eclipse-emfcloud/theia-tree-editor/blob/7850c9ecb44b3980103e667b46bc1c01de4a7eee/theia-tree-editor/src/browser/util.ts#L55

https://github.com/eclipse-emfcloud/theia-tree-editor/blob/7850c9ecb44b3980103e667b46bc1c01de4a7eee/theia-tree-editor/src/browser/util.ts#L55

[Documentation Update](https://github.com/eclipse-emfcloud/theia-tree-editor/blame/master/theia-tree-editor/DOCUMENTATION.MD#L126)

The fix would be to update `Containter` to `Container`.

**Additional Information**:
- I noticed the issue when reviewing the `tree-editor` example from the [generator-theia-extension#tree-editor](https://github.com/eclipse-theia/generator-theia-extension/tree/master/templates/tree-editor) template.

**Comment by lucas-koehler** [comment]
Thanks for reporting this! When I fix this, I'll also provide a fix for the https://github.com/eclipse-theia/generator-theia-extension/tree/master/templates/tree-editor template.

**Comment by lucas-koehler** [comment]
@vince-fugnitto The issue is fixed and updated on npm. I opened the according PR in generator-theia-extension. See mention above.
